### ISSUE TITLE
Generates NullPointerException when starting application

### ISSUE THREAD

**Issue by algorythm** [diplomit-dtu/CDIO2#2]
After 911ae7db5f638330e8104245e42300be1c862818, a NullPointerException is thrown from `FxApp` when starting.

```
java.lang.NullPointerException
	at weight.gui.FxApp.start(FxApp.java:156)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by cbudtz** [comment]
Yup - typo in code - amended now

**Comment by algorythm** [comment]
(forgot to remove following duplicate lines from FxApp):

```java			
btnexit = (Button) loader.getNamespace().get("btn_Exit");
btnexit.setOnAction(new EventHandler<ActionEvent>() { 
	@Override public void handle(ActionEvent event) { onExitButtonPressed(); }
});
```

**Comment by cbudtz** [comment]
Seems so - cleaned up now, thx
